version: "3.9"

services:
  mongo:
    image: mongo:6.0.4
    container_name: bot-spotify
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
